CREATE DATABASE products;

USE products;

CREATE TABLE product (
	product_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	subtitle VARCHAR(100) NOT NULL,
	category VARCHAR(50) NOT NULL,
	brand VARCHAR(50) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	currency CHAR(3) NOT NULL,
	stock INT UNSIGNED NOT NULL,
	description TEXT NOT NULL,
	sku VARCHAR(255) NOT NULL,
	PRIMARY KEY (product_id)
);
